name: Swift

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            TestOPT: ""
          - os: ubuntu-latest
            TestOPT: "--enable-test-discovery"

    steps:
    - uses: actions/checkout@v2
    - name: Info
      run: swift --version && echo "swift test -v $TestOPT"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: "`swift test -v $TestOPT`"
